graph LR
    A("uberon-male_organism:id-1") -- .ro-has_characteristic --> B(pato-red)
    A("uberon-male_organism:id-1") -- .ro-has_characteristic --> C(pato-convex)
    linkStyle default stroke:#0077be
